// flow-typed signature: 6900cfb74866a9f47bf29a6d264e1580
// flow-typed version: <<STUB>>/apply-loader_v^2.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apply-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apply-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'apply-loader/index' {
  declare module.exports: $Exports<'apply-loader'>;
}
declare module 'apply-loader/index.js' {
  declare module.exports: $Exports<'apply-loader'>;
}
