// flow-typed signature: 61bd1780cf0ca8cb4c38c4217cfb0288
// flow-typed version: <<STUB>>/clipboard_v^2.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipboard/dist/clipboard' {
  declare module.exports: any;
}

declare module 'clipboard/dist/clipboard.min' {
  declare module.exports: any;
}

declare module 'clipboard/karma.conf' {
  declare module.exports: any;
}

declare module 'clipboard/package' {
  declare module.exports: any;
}

declare module 'clipboard/src/clipboard-action' {
  declare module.exports: any;
}

declare module 'clipboard/src/clipboard' {
  declare module.exports: any;
}

declare module 'clipboard/test/clipboard-action' {
  declare module.exports: any;
}

declare module 'clipboard/test/clipboard' {
  declare module.exports: any;
}

declare module 'clipboard/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipboard/dist/clipboard.js' {
  declare module.exports: $Exports<'clipboard/dist/clipboard'>;
}
declare module 'clipboard/dist/clipboard.min.js' {
  declare module.exports: $Exports<'clipboard/dist/clipboard.min'>;
}
declare module 'clipboard/karma.conf.js' {
  declare module.exports: $Exports<'clipboard/karma.conf'>;
}
declare module 'clipboard/package.js' {
  declare module.exports: $Exports<'clipboard/package'>;
}
declare module 'clipboard/src/clipboard-action.js' {
  declare module.exports: $Exports<'clipboard/src/clipboard-action'>;
}
declare module 'clipboard/src/clipboard.js' {
  declare module.exports: $Exports<'clipboard/src/clipboard'>;
}
declare module 'clipboard/test/clipboard-action.js' {
  declare module.exports: $Exports<'clipboard/test/clipboard-action'>;
}
declare module 'clipboard/test/clipboard.js' {
  declare module.exports: $Exports<'clipboard/test/clipboard'>;
}
declare module 'clipboard/webpack.config.js' {
  declare module.exports: $Exports<'clipboard/webpack.config'>;
}
