// flow-typed signature: 0407a0034894a77e005e044553a93975
// flow-typed version: <<STUB>>/fullcalendar_v3.9.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fullcalendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fullcalendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fullcalendar/dist/fullcalendar' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/fullcalendar.min' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/gcal' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/gcal.min' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale-all' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/af' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar-dz' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar-kw' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar-ly' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar-ma' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar-sa' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar-tn' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ar' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/bg' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/bs' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ca' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/cs' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/da' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/de-at' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/de-ch' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/de' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/el' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/en-au' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/en-ca' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/en-gb' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/en-ie' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/en-nz' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/es-do' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/es-us' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/es' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/et' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/eu' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/fa' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/fi' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/fr-ca' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/fr-ch' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/fr' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/gl' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/he' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/hi' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/hr' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/hu' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/id' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/is' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/it' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ja' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ka' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/kk' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ko' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/lb' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/lt' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/lv' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/mk' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ms-my' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ms' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/nb' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/nl-be' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/nl' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/nn' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/pl' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/pt-br' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/pt' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ro' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/ru' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/sk' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/sl' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/sq' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/sr-cyrl' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/sr' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/sv' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/th' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/tr' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/uk' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/vi' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/zh-cn' {
  declare module.exports: any;
}

declare module 'fullcalendar/dist/locale/zh-tw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fullcalendar/dist/fullcalendar.js' {
  declare module.exports: $Exports<'fullcalendar/dist/fullcalendar'>;
}
declare module 'fullcalendar/dist/fullcalendar.min.js' {
  declare module.exports: $Exports<'fullcalendar/dist/fullcalendar.min'>;
}
declare module 'fullcalendar/dist/gcal.js' {
  declare module.exports: $Exports<'fullcalendar/dist/gcal'>;
}
declare module 'fullcalendar/dist/gcal.min.js' {
  declare module.exports: $Exports<'fullcalendar/dist/gcal.min'>;
}
declare module 'fullcalendar/dist/locale-all.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale-all'>;
}
declare module 'fullcalendar/dist/locale/af.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/af'>;
}
declare module 'fullcalendar/dist/locale/ar-dz.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar-dz'>;
}
declare module 'fullcalendar/dist/locale/ar-kw.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar-kw'>;
}
declare module 'fullcalendar/dist/locale/ar-ly.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar-ly'>;
}
declare module 'fullcalendar/dist/locale/ar-ma.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar-ma'>;
}
declare module 'fullcalendar/dist/locale/ar-sa.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar-sa'>;
}
declare module 'fullcalendar/dist/locale/ar-tn.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar-tn'>;
}
declare module 'fullcalendar/dist/locale/ar.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ar'>;
}
declare module 'fullcalendar/dist/locale/bg.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/bg'>;
}
declare module 'fullcalendar/dist/locale/bs.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/bs'>;
}
declare module 'fullcalendar/dist/locale/ca.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ca'>;
}
declare module 'fullcalendar/dist/locale/cs.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/cs'>;
}
declare module 'fullcalendar/dist/locale/da.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/da'>;
}
declare module 'fullcalendar/dist/locale/de-at.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/de-at'>;
}
declare module 'fullcalendar/dist/locale/de-ch.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/de-ch'>;
}
declare module 'fullcalendar/dist/locale/de.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/de'>;
}
declare module 'fullcalendar/dist/locale/el.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/el'>;
}
declare module 'fullcalendar/dist/locale/en-au.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/en-au'>;
}
declare module 'fullcalendar/dist/locale/en-ca.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/en-ca'>;
}
declare module 'fullcalendar/dist/locale/en-gb.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/en-gb'>;
}
declare module 'fullcalendar/dist/locale/en-ie.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/en-ie'>;
}
declare module 'fullcalendar/dist/locale/en-nz.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/en-nz'>;
}
declare module 'fullcalendar/dist/locale/es-do.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/es-do'>;
}
declare module 'fullcalendar/dist/locale/es-us.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/es-us'>;
}
declare module 'fullcalendar/dist/locale/es.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/es'>;
}
declare module 'fullcalendar/dist/locale/et.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/et'>;
}
declare module 'fullcalendar/dist/locale/eu.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/eu'>;
}
declare module 'fullcalendar/dist/locale/fa.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/fa'>;
}
declare module 'fullcalendar/dist/locale/fi.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/fi'>;
}
declare module 'fullcalendar/dist/locale/fr-ca.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/fr-ca'>;
}
declare module 'fullcalendar/dist/locale/fr-ch.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/fr-ch'>;
}
declare module 'fullcalendar/dist/locale/fr.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/fr'>;
}
declare module 'fullcalendar/dist/locale/gl.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/gl'>;
}
declare module 'fullcalendar/dist/locale/he.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/he'>;
}
declare module 'fullcalendar/dist/locale/hi.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/hi'>;
}
declare module 'fullcalendar/dist/locale/hr.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/hr'>;
}
declare module 'fullcalendar/dist/locale/hu.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/hu'>;
}
declare module 'fullcalendar/dist/locale/id.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/id'>;
}
declare module 'fullcalendar/dist/locale/is.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/is'>;
}
declare module 'fullcalendar/dist/locale/it.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/it'>;
}
declare module 'fullcalendar/dist/locale/ja.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ja'>;
}
declare module 'fullcalendar/dist/locale/ka.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ka'>;
}
declare module 'fullcalendar/dist/locale/kk.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/kk'>;
}
declare module 'fullcalendar/dist/locale/ko.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ko'>;
}
declare module 'fullcalendar/dist/locale/lb.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/lb'>;
}
declare module 'fullcalendar/dist/locale/lt.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/lt'>;
}
declare module 'fullcalendar/dist/locale/lv.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/lv'>;
}
declare module 'fullcalendar/dist/locale/mk.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/mk'>;
}
declare module 'fullcalendar/dist/locale/ms-my.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ms-my'>;
}
declare module 'fullcalendar/dist/locale/ms.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ms'>;
}
declare module 'fullcalendar/dist/locale/nb.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/nb'>;
}
declare module 'fullcalendar/dist/locale/nl-be.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/nl-be'>;
}
declare module 'fullcalendar/dist/locale/nl.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/nl'>;
}
declare module 'fullcalendar/dist/locale/nn.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/nn'>;
}
declare module 'fullcalendar/dist/locale/pl.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/pl'>;
}
declare module 'fullcalendar/dist/locale/pt-br.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/pt-br'>;
}
declare module 'fullcalendar/dist/locale/pt.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/pt'>;
}
declare module 'fullcalendar/dist/locale/ro.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ro'>;
}
declare module 'fullcalendar/dist/locale/ru.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/ru'>;
}
declare module 'fullcalendar/dist/locale/sk.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/sk'>;
}
declare module 'fullcalendar/dist/locale/sl.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/sl'>;
}
declare module 'fullcalendar/dist/locale/sq.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/sq'>;
}
declare module 'fullcalendar/dist/locale/sr-cyrl.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/sr-cyrl'>;
}
declare module 'fullcalendar/dist/locale/sr.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/sr'>;
}
declare module 'fullcalendar/dist/locale/sv.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/sv'>;
}
declare module 'fullcalendar/dist/locale/th.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/th'>;
}
declare module 'fullcalendar/dist/locale/tr.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/tr'>;
}
declare module 'fullcalendar/dist/locale/uk.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/uk'>;
}
declare module 'fullcalendar/dist/locale/vi.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/vi'>;
}
declare module 'fullcalendar/dist/locale/zh-cn.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/zh-cn'>;
}
declare module 'fullcalendar/dist/locale/zh-tw.js' {
  declare module.exports: $Exports<'fullcalendar/dist/locale/zh-tw'>;
}
