// flow-typed signature: 4746ab353c5c3ca127e6611d9bcc471d
// flow-typed version: <<STUB>>/ical.js_v^1.2.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ical.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ical.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ical.js/build/ical' {
  declare module.exports: any;
}

declare module 'ical.js/build/ical.min' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/binary' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/component_parser' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/component' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/design' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/duration' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/event' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/helpers' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/parse' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/period' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/property' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/recur_expansion' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/recur_iterator' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/recur' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/stringify' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/time' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/timezone_service' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/timezone' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/utc_offset' {
  declare module.exports: any;
}

declare module 'ical.js/lib/ical/vcard_time' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ical.js/build/ical.js' {
  declare module.exports: $Exports<'ical.js/build/ical'>;
}
declare module 'ical.js/build/ical.min.js' {
  declare module.exports: $Exports<'ical.js/build/ical.min'>;
}
declare module 'ical.js/lib/ical/binary.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/binary'>;
}
declare module 'ical.js/lib/ical/component_parser.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/component_parser'>;
}
declare module 'ical.js/lib/ical/component.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/component'>;
}
declare module 'ical.js/lib/ical/design.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/design'>;
}
declare module 'ical.js/lib/ical/duration.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/duration'>;
}
declare module 'ical.js/lib/ical/event.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/event'>;
}
declare module 'ical.js/lib/ical/helpers.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/helpers'>;
}
declare module 'ical.js/lib/ical/parse.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/parse'>;
}
declare module 'ical.js/lib/ical/period.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/period'>;
}
declare module 'ical.js/lib/ical/property.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/property'>;
}
declare module 'ical.js/lib/ical/recur_expansion.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/recur_expansion'>;
}
declare module 'ical.js/lib/ical/recur_iterator.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/recur_iterator'>;
}
declare module 'ical.js/lib/ical/recur.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/recur'>;
}
declare module 'ical.js/lib/ical/stringify.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/stringify'>;
}
declare module 'ical.js/lib/ical/time.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/time'>;
}
declare module 'ical.js/lib/ical/timezone_service.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/timezone_service'>;
}
declare module 'ical.js/lib/ical/timezone.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/timezone'>;
}
declare module 'ical.js/lib/ical/utc_offset.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/utc_offset'>;
}
declare module 'ical.js/lib/ical/vcard_time.js' {
  declare module.exports: $Exports<'ical.js/lib/ical/vcard_time'>;
}
