// flow-typed signature: 47d84e33ea7fe1e05060e88b77f27b91
// flow-typed version: <<STUB>>/iframe-resizer_v^3.5.14/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iframe-resizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iframe-resizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iframe-resizer/gruntfile' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/ie8.polyfils.min' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer.contentWindow' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer.contentWindow.min' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer.min' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/index' {
  declare module.exports: any;
}

declare module 'iframe-resizer/karma.conf' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/_initSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/anchorSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/childSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/closeSpecSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/getPageInfoSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/initCssSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/initDomSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/initDoubleCallSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/initErrorSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/initJQuerySpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/initUndefinedDomSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/lib/common' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/parentSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/scrollSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/spec/sendMessageSpec' {
  declare module.exports: any;
}

declare module 'iframe-resizer/src/ie8.polyfils' {
  declare module.exports: any;
}

declare module 'iframe-resizer/src/iframeResizer.contentWindow' {
  declare module.exports: any;
}

declare module 'iframe-resizer/src/iframeResizer' {
  declare module.exports: any;
}

declare module 'iframe-resizer/test-main' {
  declare module.exports: any;
}

declare module 'iframe-resizer/test/resources/jquery' {
  declare module.exports: any;
}

declare module 'iframe-resizer/test/resources/qunit' {
  declare module.exports: any;
}

declare module 'iframe-resizer/test/resources/require' {
  declare module.exports: any;
}

declare module 'iframe-resizer/test/resources/testLib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iframe-resizer/gruntfile.js' {
  declare module.exports: $Exports<'iframe-resizer/gruntfile'>;
}
declare module 'iframe-resizer/index' {
  declare module.exports: $Exports<'iframe-resizer'>;
}
declare module 'iframe-resizer/index.js' {
  declare module.exports: $Exports<'iframe-resizer'>;
}
declare module 'iframe-resizer/js/ie8.polyfils.min.js' {
  declare module.exports: $Exports<'iframe-resizer/js/ie8.polyfils.min'>;
}
declare module 'iframe-resizer/js/iframeResizer.contentWindow.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer.contentWindow'>;
}
declare module 'iframe-resizer/js/iframeResizer.contentWindow.min.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer.contentWindow.min'>;
}
declare module 'iframe-resizer/js/iframeResizer.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer'>;
}
declare module 'iframe-resizer/js/iframeResizer.min.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer.min'>;
}
declare module 'iframe-resizer/js/index.js' {
  declare module.exports: $Exports<'iframe-resizer/js/index'>;
}
declare module 'iframe-resizer/karma.conf.js' {
  declare module.exports: $Exports<'iframe-resizer/karma.conf'>;
}
declare module 'iframe-resizer/spec/_initSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/_initSpec'>;
}
declare module 'iframe-resizer/spec/anchorSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/anchorSpec'>;
}
declare module 'iframe-resizer/spec/childSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/childSpec'>;
}
declare module 'iframe-resizer/spec/closeSpecSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/closeSpecSpec'>;
}
declare module 'iframe-resizer/spec/getPageInfoSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/getPageInfoSpec'>;
}
declare module 'iframe-resizer/spec/initCssSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/initCssSpec'>;
}
declare module 'iframe-resizer/spec/initDomSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/initDomSpec'>;
}
declare module 'iframe-resizer/spec/initDoubleCallSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/initDoubleCallSpec'>;
}
declare module 'iframe-resizer/spec/initErrorSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/initErrorSpec'>;
}
declare module 'iframe-resizer/spec/initJQuerySpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/initJQuerySpec'>;
}
declare module 'iframe-resizer/spec/initUndefinedDomSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/initUndefinedDomSpec'>;
}
declare module 'iframe-resizer/spec/lib/common.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/lib/common'>;
}
declare module 'iframe-resizer/spec/parentSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/parentSpec'>;
}
declare module 'iframe-resizer/spec/scrollSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/scrollSpec'>;
}
declare module 'iframe-resizer/spec/sendMessageSpec.js' {
  declare module.exports: $Exports<'iframe-resizer/spec/sendMessageSpec'>;
}
declare module 'iframe-resizer/src/ie8.polyfils.js' {
  declare module.exports: $Exports<'iframe-resizer/src/ie8.polyfils'>;
}
declare module 'iframe-resizer/src/iframeResizer.contentWindow.js' {
  declare module.exports: $Exports<'iframe-resizer/src/iframeResizer.contentWindow'>;
}
declare module 'iframe-resizer/src/iframeResizer.js' {
  declare module.exports: $Exports<'iframe-resizer/src/iframeResizer'>;
}
declare module 'iframe-resizer/test-main.js' {
  declare module.exports: $Exports<'iframe-resizer/test-main'>;
}
declare module 'iframe-resizer/test/resources/jquery.js' {
  declare module.exports: $Exports<'iframe-resizer/test/resources/jquery'>;
}
declare module 'iframe-resizer/test/resources/qunit.js' {
  declare module.exports: $Exports<'iframe-resizer/test/resources/qunit'>;
}
declare module 'iframe-resizer/test/resources/require.js' {
  declare module.exports: $Exports<'iframe-resizer/test/resources/require'>;
}
declare module 'iframe-resizer/test/resources/testLib.js' {
  declare module.exports: $Exports<'iframe-resizer/test/resources/testLib'>;
}
