// flow-typed signature: 605741203cee25b0c64b5ef651f1d796
// flow-typed version: <<STUB>>/iframe-resizer_v^3.5.14/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iframe-resizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iframe-resizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'iframe-resizer/js/ie8.polyfils.min' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer.contentWindow' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer.contentWindow.min' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/iframeResizer.min' {
  declare module.exports: any;
}

declare module 'iframe-resizer/js/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'iframe-resizer/index' {
  declare module.exports: $Exports<'iframe-resizer'>;
}
declare module 'iframe-resizer/index.js' {
  declare module.exports: $Exports<'iframe-resizer'>;
}
declare module 'iframe-resizer/js/ie8.polyfils.min.js' {
  declare module.exports: $Exports<'iframe-resizer/js/ie8.polyfils.min'>;
}
declare module 'iframe-resizer/js/iframeResizer.contentWindow.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer.contentWindow'>;
}
declare module 'iframe-resizer/js/iframeResizer.contentWindow.min.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer.contentWindow.min'>;
}
declare module 'iframe-resizer/js/iframeResizer.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer'>;
}
declare module 'iframe-resizer/js/iframeResizer.min.js' {
  declare module.exports: $Exports<'iframe-resizer/js/iframeResizer.min'>;
}
declare module 'iframe-resizer/js/index.js' {
  declare module.exports: $Exports<'iframe-resizer/js/index'>;
}
