// flow-typed signature: 938be676ee5808b5df460642f33afeb9
// flow-typed version: <<STUB>>/linkify-it_v^2.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'linkify-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'linkify-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'linkify-it/lib/re' {
  declare module.exports: any;
}

// Filename aliases
declare module 'linkify-it/index' {
  declare module.exports: $Exports<'linkify-it'>;
}
declare module 'linkify-it/index.js' {
  declare module.exports: $Exports<'linkify-it'>;
}
declare module 'linkify-it/lib/re.js' {
  declare module.exports: $Exports<'linkify-it/lib/re'>;
}
