// flow-typed signature: dacfeaf76473fc30851ffcbdad75fa38
// flow-typed version: <<STUB>>/styled-jsx-postcss_v^0.2.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-jsx-postcss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-jsx-postcss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-jsx-postcss/babel' {
  declare module.exports: any;
}

declare module 'styled-jsx-postcss/dist/babel' {
  declare module.exports: any;
}

declare module 'styled-jsx-postcss/dist/processor' {
  declare module.exports: any;
}

declare module 'styled-jsx-postcss/server' {
  declare module.exports: any;
}

declare module 'styled-jsx-postcss/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-jsx-postcss/babel.js' {
  declare module.exports: $Exports<'styled-jsx-postcss/babel'>;
}
declare module 'styled-jsx-postcss/dist/babel.js' {
  declare module.exports: $Exports<'styled-jsx-postcss/dist/babel'>;
}
declare module 'styled-jsx-postcss/dist/processor.js' {
  declare module.exports: $Exports<'styled-jsx-postcss/dist/processor'>;
}
declare module 'styled-jsx-postcss/server.js' {
  declare module.exports: $Exports<'styled-jsx-postcss/server'>;
}
declare module 'styled-jsx-postcss/style.js' {
  declare module.exports: $Exports<'styled-jsx-postcss/style'>;
}
