// flow-typed signature: 1a6a8ea4cfec78e45c0ac0903d29dde8
// flow-typed version: <<STUB>>/typeface-noto-sans_v^0.0.35/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-noto-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-noto-sans' {
  declare module.exports: any;
}
