// flow-typed signature: 57a28fb77d6336df68b2cc2113ce96d1
// flow-typed version: <<STUB>>/typeface-noto-sans_v^0.0.54/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-noto-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-noto-sans' {
  declare module.exports: any;
}
